name = "gemini-ocr-worker"
main = "src/index.js" # 主 Worker 脚本位于 src/ 目录
compatibility_date = "2025-09-07"
compatibility_flags = [ "nodejs_compat" ]

# [assets] 定义了静态资源的位置。
# Worker 会将所有前端文件从这个 "public" 目录提供服务。
[assets]
directory = "./public"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
